### ISSUE TITLE
Does this support IPv6 tethering?

### ISSUE THREAD

**Issue by linhua55** [Mygod/DHCPv6-Client-Android#1]
Recently, China is deploying IPv6 on mobile network. I want to access IPv6 network through tethering(USB tethering or WIFI tethering). But my mobile android version is 6.0. By default, android 6.0 doesn't support IPv6 tethering. 

https://android.stackexchange.com/questions/181361/does-android-have-support-for-ipv6-tethering

I found that IPv6 tethering is related to DHCPv6.

https://groups.google.com/d/msg/tmoipv6beta/z6EVpEkzqkQ/OUTYgOIkmLIJ
https://tools.ietf.org/html/draft-byrne-v6ops-64share-03

Does this be able to implement IPv6 tethering on android 6.0 ?  Thanks.

**Comment by Mygod** [comment]
Hello. As I pointed out in the stackexchange question you quoted, recent Android versions supports IPv6 tethering natively - so long as the carrier provides support as well. And China Telecom already supports IPv6 tethering.

I need to point out that [DHCPv6 is a worse solution compared to SLAAC](https://rule11.tech/slaac-and-dhcpv6/). Any carrier that uses only DHCPv6 in their stack should realize that they're dropping support for [all unrooted Android phones](https://issuetracker.google.com/issues/36949085). Which carrier are you using and are you sure they are using DHCPv6 as their IPv6 solution?

Finally, just for future reference, to do DHCPv6 tethering, the very first step is to obtain a IPv6 block using DHCPv6 PD (Prefix Delegation) which isn't supported by this app yet, but you can tweak the configuration file (`dhcp6c.conf`) and invoke the binary manually to see if that's possible.

**Comment by linhua55** [comment]
![screenshot_2018-07-22-19-42-13-694_com android chrome](https://user-images.githubusercontent.com/6326116/43045257-e6877aa8-8de7-11e8-8969-5aaf6b1b29bb.png)

Oh, It's your answer.

If I  manually customize IPv6 address and IPv6 gateway for tethered network interface on my computer. Will it work? According to my knowledge, in IPv6 network,  the IPv6 address is public address instead of private address, and every computer has a unique and  fix IPv6 address just like MAC address.

**Comment by Mygod** [comment]
Are you using this app to obtain an IPv6 address or can your system obtain an IPv6 address automatically?

**Comment by linhua55** [comment]
I haven't use this APP. It obtain IPv6 address automatically.

**Comment by Mygod** [comment]
Android doesn't support DHCPv6 natively so I think you are probably using SLAAC?

**Comment by Mygod** [comment]
Also just to clear up confusion, IPv6 tethering can also use SLAAC, which has already been implemented in latest Android versions for mobile data IPv6 tethering.
