### ISSUE TITLE
Doesn't work on android 9

### ISSUE THREAD

**Issue by showgood163** [Mygod/DHCPv6-Client-Android#2]
Oneplus 6
Working on H2os@android 8.1
After I upgrade to O2os@android 9.0, this app doesn't work anymore.

**Comment by Mygod** [comment]
Clear app data?

**Comment by showgood163** [comment]
Force stop,.clear data and rerun.
Not working.

**Comment by Mygod** [comment]
This app has been tested on LineageOS 16. I'm not sure why it's not working. Can you please grab a logcat?

**Comment by showgood163** [comment]
Sorry, after a few reboots(?) this app starts working.
I also have a strong feeling that this version(180915) of O2os is not stable enough to be the daily driver.
Here's the logcat.
[logcat.txt](https://github.com/Mygod/DHCPv6-Client-Android/files/2456878/3.txt)

**Comment by Mygod** [comment]
This app seems to be working fine during the time your log has covered. I guess I'll close this for now. Feel free to update when you get a logcat as soon as it's not working.

**Comment by showgood163** [comment]
[logcat.txt](https://github.com/Mygod/DHCPv6-Client-Android/files/2543293/logcat.txt)

@Mygod 
It's not working as long as I'm using O2OS Pie ROM.
Reboot doesn't seem to work.
Software version 1.3.0.

**Comment by Mygod** [comment]
@showgood163 Sorry for the late reply. But looking at your log, I don't think there's a DHCPv6 server reachable. For example:

```
11-03 00:20:53.222 11477 11671 I libdhcp6c.so: Nov/03/2018 00:20:53: copy_option: set client ID (len 14)
11-03 00:20:53.223 11477 11671 I libdhcp6c.so: Nov/03/2018 00:20:53: copyout_option: set identity association
11-03 00:20:53.223 11477 11671 I libdhcp6c.so: Nov/03/2018 00:20:53: copy_option: set elapsed time (len 2)
11-03 00:20:53.223 11477 11671 I libdhcp6c.so: Nov/03/2018 00:20:53: copy_option: set option request (len 4)
11-03 00:20:53.223 11477 11671 I libdhcp6c.so: Nov/03/2018 00:20:53: client6_send: send solicit to ff02::1:2%wlan0
11-03 00:20:53.223 11477 11671 I libdhcp6c.so: Nov/03/2018 00:20:53: dhcp6_reset_timer: reset a timer on wlan0, state=SOLICIT, timeo=5, retrans=34234
(no response is received)
```

**Comment by showgood163** [comment]
@Mygod

Emmm.. I didn't think the network environment has changed before or after I changed the rom.
For now, I'm using O2OS 5.1.11(8.1.0) and dhcpv6 1.3.0 and for now it works occasionally, not always, which may be coincident with the analysis you provided.
I may get back to O2OS 9.0.2 if I have time and get more log for this problem.
