### ISSUE TITLE
exit(1) on Android 8.1 on MIUI

### ISSUE THREAD

**Issue by linzuzeng** [Mygod/DHCPv6-Client-Android#3]
exit(1) on Android 8.1 on a Xiaomi Device
Fresh rooted with busybox installed. 
Logcat only shows "failed to get a DUID."

**Comment by Mygod** [comment]
Full logcat?

**Comment by linzuzeng** [comment]
[logcat-1101-121809.log](https://github.com/Mygod/DHCPv6-Client-Android/files/2537208/logcat-1101-121809.log)

**Comment by Mygod** [comment]
Can you try 1.2.1?

**Comment by linzuzeng** [comment]
No it doesn't work. same error. 

however, the realmars program works on my phone, but it requires busybox installation which would be removed on every OTA update. to

**Comment by Mygod** [comment]
I think the problem should be that your LBE su doesn't respect CWD unlike other sus like Magisk or SuperSU.

**Comment by linzuzeng** [comment]
Is it possible to integrate a busybox or something similar to run the scripts?

**Comment by Mygod** [comment]
I'll fix this in the next update.

**Comment by linzuzeng** [comment]
I was trying to fix this problem but I couldn't find where CWD happened. Will bypassing get_duid solve this problem?

**Comment by Mygod** [comment]
Sorry for the delay. I will get to fix this sometime soon.

**Comment by linzuzeng** [comment]
Thank you very much! 
The latest update of MIUI made it impossible to install busybox, thus realmars program would not work anymore.

**Comment by Mygod** [comment]
Try 1.4.0.
