### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by dllud** [Mygod/DHCPv6-Client-Android#7]
It would be much handy if this app could be added into F-Droid. I was [warned to the fact that you already have one app there](https://gitlab.com/fdroid/fdroiddata/issues/1950#note_288886998). I hope it is a familiar procedure already.

Although this app is [released under Apache 2.0](https://github.com/Mygod/DHCPv6-Client-Android/blob/master/LICENSE), it seems to be [using non-free libs](https://github.com/Mygod/DHCPv6-Client-Android/blob/master/mobile/build.gradle#L103), perhaps for analytics or advertisement. I guess such will have to be removed before inclusion into F-Droid.

**Comment by Mygod** [comment]
No.

**Comment by Perflyst** [comment]
Why?
Also `No closed source components` but you added crashlytics, firebase and gms?!
